technologies = ['databricks', 'JUnit', 'cucumber', 'vue', 'nunit', 'windows', 'cocoa touch', 
'Prometheus', 'user experience (ux) design', 'Postman', 'zend', 'azure data services', 
'restful apis', 'jasmine', 'rollup', 'microsoft dynamics', 'github actions', 'nuget', 
'arcore', 'hyperledger', 'tensorflow', 'Ansible', 'TestRail', 'boto3', 'Burp Suite', 
'Gatling', 'parcel', 'Git', 'adobe xd', 'php', 'ant', 'shiny', 'jenkins', 'teamcity', 
'caret', 'dapp development', 'jakarta ee', 'salesforce', 'MongoDB', 'user interface (ui) design', 
'scrapy', 'cypress', 'symfony', 'terraform', 'tdd', 'github', 'embedded c', 'httpx', 
'gitlab ci', 'owasp', 'codeception', 'JSON', 'vue-router', 'minitest', 'Metasploit', 
'dask', 'solidity', 'apache kafka', 'vmware', 'Bitbucket', 'sklearn', 'next.js', 
'MITRE ATT&CK', 'struts', 'cassandra', 'r', 'google cloud platformgcp', 'twisted', 
'prometheus', 'sqlalchemy', 'stylelint', 'puppet', 'angular', 'Tableau Bridge', 'scrum', 
'Babel', 'postman', 'Jenkins', 'aws', 'identitynow', 'gitlab ci/cd', 'Puppet', 'beego', 
'asyncio', 'macos', 'cakephp', 'tornado', 'dns', 'rust', 'vue.js', 'virtualbox', 'grunt', 
'hiveql', 'sails.js', 'mongodb', 'seaborn','iot' , 'jquery', 'react.js', 'power bi desktop', 
'apex', 'file system', 'selenium', 'VMware', 'Azure', 'Cucumber', 'salesforce dx', 'xctest', 
'tox', 'dash', 'jquerypython', 'svelte', 'quick', 'figma', 'kitura', 'nimble', 
'salesforce service cloud', 'OSINT', 'oculus sdk', 'ios', 'travis ci', 'flutter', 
'tornadoexpress.js', 'togaf', 'click', 'devops', 'eslint', 'react', 'kotlin', 'jest', 
'dplyr', 'powershell', 'Tableau Online', 'elasticsearch', 'perl', 'dynamodb', 'phpunit', 
'observer', 'GitLab', 'fabric', 'VirtualBox', 'intellij idea', 'LoadRunner', 'sonarqube', 
'airflow', 'gradle', 'mariadb', 'pydantic', 'new relic', 'mstest', 'fastapi', 'rabbitmq', 
'sinatra', 'nagios', 'drupal', 'typescript', 'catboost', 'archimate', 'zoho crm', 'Chef', 
'visual studio code', 'hive', 'java', 'html/css', 'graphql', 'sap', 'penetration testing', 
'hibernate', 'eclipse', 'swift', 'angular.js', 'arduino', 'machine learning', 'phoenix', 
'c', 'usability testing', 'gin', 'Nagios', 'gensim', 'bootstrap', 'scipy', 
'oracle enterprise manager', 'kafka', 'lxml', 'NIST Cybersecurity Framework', 'tableau', 
'raspberry pi', 'Nmap', 'requests', 'enterprise service bus', 'test-driven development', 
'vapor', 'scikit-learn', 'actix', 'msbuild', 'json', 'Windows Server', 'nosql', 'mocha', 
'strategy', 'android sdk', 'hubspot', 'Linux', 'redux', 'spring', 'behat', 'hadoop', 
'power bi', 'helm', 'matlab', 'waterfall', 'entity framework', 'unreal engine', 
'oracle sql developer', 'big data analytics', 'html', 'log4net', 'echo', 'AWS Security', 
'elixirmysql', 'SQL databases', 'Node.js', 'ansible', 'REST Assured', 'apache commons', 
'amazon web services', 'git', 'JIRA', 'Zabbix', 'CircleCI', 'log4j', 'gcp', 'testng', 
'heroku', 'objective-c', 'qiskit', 'deep learning', 'sql', 'Selenium', 'spark', 'Excel', 
'luigi', 'pyspark', 'pytz', 'load balancing', 'meteor', 'numpy', 'firebase', 'datadog', 
'javascript', 'Mocha', 'urllib3', 'rails', 'nhibernate', 'GCP', 'storm', 'yii', 'jupyter', 
'textblob', 'joomla', 'TestNG', 'maven', 'soap', 'flask', 'React.js', 'gitlab', 'nestjs', 
'unity', 'jsf', 'Cypress', 'argparse', 'ruby on rails', 'linux', 'azure', 'salesforce crm', 
'asp.net', 'adapter', 'GitHub Actions', 'espresso', 'PowerShell', 'couchdbdjango', 'ktor', 
'bitbucket', 'node.js', 'azure devops', 'unit testing', '.net', 'bamboo', 'Express.js', 
'unittest', 'pandas', 'ui-ux', 'android studio', 'junit', 'cobol', 'gogo', 'encryption', 
'power automate', 'openshift', 'randomforest', 'vuex', 'FI/CO', 'SAP ERP', 'factory', 
'azure logic apps', 'esb', 'SAP BW/4HANA', 'asp.net core', 'postgresql', 'redis', 
'apache camel', 'Tableau Server', 'identityiq', 'lightgbm', 'python', 'xgboost', 'ggplot2', 
'vue-cli', 'android', 'pillow', 'peewee', 'hyper-v', 'interplanetary', 'hbase', 'pyramid', 
'sketch', 'swiftui', 'codeigniter', 'AWS', 'network security', 'oracle erp', 'xcode', 
'proto.io', 'GCP Security', 'axure', 'Wireshark', 'Tableau Desktop', 'GitHub', 'specflow', 
'web services', 'gulp', 'rocket', 'ethereum', 'bokeh', 'guava', 'CSV', 'sql server', 
'slf4j', 'visualforce', 'microsoft q#', 'ros', 'sqlite', 'JMeter', 'HANA', 'Azure Security', 
'Travis CI', 'keras', 'Enzyme', 'Shell scripting', 'oracle database', 'Kali Linux', 
'circleci', 'SAP Fiori', 'karma', 'pytest', 'padrino', 'plotly', 'docker', 'mockito', 
'web2py', 'Webpack', 'agile', 'blazor', 'mysql', 'spring boot', 'saltstack', 'flink', 
'kanban', 'activemq', 'react native', 'micronaut', 'elk stack', 'Hyper-V', 'Chai', 'css', 
'integration testing', 'tcp/ip', 'ruby', 'Tableau Prep', 'hanami', 'bash', 'xunit', 
'nuxt.js', 'webpack', 'aiohttp', 'c#', 'jshint', 'Google Sheets', 'jira', 'ABAP', 
'statsmodels', 'pl/sql', 'wordpress', 'arkit', 'pony orm', 'pytorch', 'scala', 
'beautifulsoup', 'c++', 'http/https', 'vaadin', 'fortran', 'javaserver faces', 
'microservices', 'robot operating system', 'singleton', 'spacy', 'opencv', 'kubeflow', 
'tailwind css', 'salesforce cloud', 'kubernetes', 'SAP S/4HANA', 'serilog', 
'smart contracts', 'dapper', 'chef', 'celery', 'nose', 'grafana', 'mlflow', 
'power bi service', 'Jest', 'hypothesis', 'invision', 'google cloud', 'ipfs', 
'bottle', 'laravel', 'express.js', 'vagrant', 'excel', 'pig', 'xml', 'cocos2d', 
'mobx', 'splunk', 'django', 'nltk', 'oracle', 'matplotlib', 'django orm', 'play', 
'salesforce lightning', 'rspec']